<?xml version="1.0"?>
<package format="3">
  <name>go2_object_explorer</name>
  <version>0.2.0</version>
  <description>Frontier-based Omi ObjectNav explorer for Unitree Go2 using YOLOv8 and optional SAM2.</description>
  <maintainer email="pateldhruv1672@gmail.com">Dhruv Patel</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>cv_bridge</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
  <depend>rcl_interfaces</depend>
</package>
